### PR TITLE
Feature - Purchase Optimization

### PR DESCRIPTION
**Pull request by flomarin88**
As a simracer who
- don't own every tracks yet
- wants to focus on his/her favorite series
- had a small budget
 I want to smart buy my next tracks to optimize my planning

The "Purchase Guide" will tell you which unowned Tracks are used multiple times in your favorites series.
Screenshot 2020-04-22 at 00 15 31

With a single click on the basket icon, you are directly redirected on iRacing / Track page to buy it.

### CODE REVIEW

**Comment by tmoitie** [comment]
Hi, thanks for the PR. There are a lot of changes here which are pure code style but deviate from the airbnb standard - e.g. everywhere where you've removed spaces from inside braces. Could you revert the codestyle changes and only leave the substantiative changes? Ideally could you check your code against eslint?

Thanks!

**Comment by flomarin88** [comment]
I cleaned some files.

When I check the code with eslint, I still get + 200 errors on untouched files
Screenshot 2020-04-22 at 17 11 57

**Comment by flomarin88** [comment]
Thanks @tmoitie

**Comment by tmoitie** [comment]
Thank you!

**Pull request merged**
