### PR TITLE
it.js

### PR DESCRIPTION
**Pull request by alexz23-96**
Italian translation - Not completed yet. I will continue the traslation douring my free time.
Can you enable me for edit the file?

### CODE REVIEW

**Comment by tmoitie** [comment]
Hi! You can continue to edit the file here:
https://github.com/alexz23-96/iRacing-week-planner/blob/patch-1/translations/it

And it will automatically update this pull request :)

Thank you so much!

**Comment by alexz23-96** [comment]
Hi! I'm happy to help you! :)
I translated all yesterday!
I need only a information: Can i modify the parts with {xxx} ?

**Comment by tmoitie** [comment]
No everything in the {{}} should be kept as english - They won't show to the user as english, they are placeholders to put other text in

**Comment by alexz23-96** [comment]
Well! I translated all, and all section with {{xxx}} now are withtout translation!
Sey me if need other correction! ;-)

**Pull request merged**
