### PR TITLE
Improve Spanish translations

### PR DESCRIPTION
**Pull request by sergioalmela**
Improve some Spanish strings, and modify some others to make them look more human.
TODO: We are using formal and informal language indiscriminately.

### CODE REVIEW

**Comment by sergioalmela** [comment]
Should we use formal or informal language here?

**Comment by tmoitie** [comment]
It depends, what would you normally expect to see on any given website? I'm relying on the community for these translations as I'm no multilingualist. Whichever you feel would be best, I'm happy to push forwards with either. 

Thank you for contributing your time and language!

**Comment by sergioalmela** [comment]
Done, as most of the webpages uses formal language

**Comment by tmoitie** [comment]
Muchas gracias

**Pull request merged**
